Completed the prep-example excercise
DreSean-Sutton/prep-91621-code-solutions pull request #1
Opened 2021-09-18 19:24 UTC by DreSean-Sutton

![Screenshot 2021-09-18 122321](https://user-images.githubusercontent.com/90172283/133906300-47a8f94e-f8bb-4a59-bd99-a92a8a3b5877.png)

2021-09-18 20:28 UTC, thebearingedge requested changes

2021-09-18 20:28 UTC, thebearingedge commented on prep-example.tar/index.html
> +
Hi Dre, looks like your note didn't make it into the HTML file.

2021-09-19 05:17 UTC, DreSean-Sutton commented
![Annotation 2019-12-23 210634](https://user-images.githubusercontent.com/90172283/133916357-11db98ea-248a-415a-ad62-7cba90b83098.png)

2021-09-19 14:45 UTC, thebearingedge approved these changes

2021-09-25 03:06 UTC, merged