Finished flexbox assignment!
DreSean-Sutton/prep-91621-code-solutions pull request #8
Opened 2021-09-24 05:01 UTC by DreSean-Sutton

![image](https://user-images.githubusercontent.com/90172283/134620779-7690996e-a821-4008-87a5-9f3e9837196c.png)

![image](https://user-images.githubusercontent.com/90172283/134620807-f1a40e60-75d1-49ca-aa77-8a928cdb0b75.png)

![image](https://user-images.githubusercontent.com/90172283/134620825-cbdcf2e6-2715-48b0-81c2-e2824dc82e12.png)

![image](https://user-images.githubusercontent.com/90172283/134620846-eced2181-7b19-4457-a042-dcfcfb7450d8.png)

2021-09-25 15:55 UTC, thebearingedge requested changes

2021-09-25 15:55 UTC, thebearingedge commented on prep-css-flexbox/align-items.html
> +    }
Hi Dre, to get your card centered on the page, try adding `align-items: center` to this rule set.

2021-09-25 17:44 UTC, DreSean-Sutton commented
![image](https://user-images.githubusercontent.com/90172283/134781082-308b23b9-b572-4bc6-876d-3e2e1ed3d379.png)

2021-09-27 16:33 UTC, thebearingedge approved these changes

2021-09-29 03:23 UTC, merged